src/Entity/TestSearch.php
<?php
/**
 * User: Andrey Shamis
 * Date: 02.07.18
 * Time: 12:30
 */

namespace App\Entity;


class TestSearch
{

    protected $name = '';

    protected $verdicts;

    protected $setups;

    protected $fromDate;

    protected $toDate;

    /** @var int  */
    protected $limit=2000;

    public static $MAX_LIMIT = 10000;

    public static $DEFAULT_LIMIT = 2000;
    /**
     * @return int
     */
    public function getLimit(): int
    {
        if ($this->limit < 1 || $this->limit > self::$MAX_LIMIT ) {
            $this->setLimit(self::$DEFAULT_LIMIT);
        }
        return $this->limit;
    }

    /**
     * @param int $limit
     */
    public function setLimit(int $limit = null): void
    {
        if ($limit === null) {
            $this->limit = self::$DEFAULT_LIMIT;
        } else {
            $this->limit = $limit;
        }
    }

    /**
     * @return mixed
     */
    public function getToDate()
    {
        return $this->toDate;
    }

    /**
     * @param mixed $toDate
     */
    public function setToDate($toDate): void
    {
        $this->toDate = $toDate;
    }

    /**
     * @return mixed
     */
    public function getFromDate()
    {
        return $this->fromDate;
    }

    /**
     * @param mixed $fromDate
     */
    public function setFromDatet($fromDate): void
    {
        $this->fromDate = $fromDate;
    }

    /**
     * @return string
     */
    public function getCycle(): ?string
    {
        return '';
    }

    /**
     * @param string $cycle
     */
    public function setCycle(string $cycle = null): void
    {
        return;
    }

    /**
     * @return string
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * @param string $name
     */
    public function setName(string $name = null): void
    {
        $this->name = $name;
    }

    /**
     * @return LogBookVerdict[]
     */
    public function getVerdict(): ?array
    {
        return $this->verdicts;
    }

    /**
     * @param LogBookVerdict[] $verdicts
     */
    public function setVerdict(LogBookVerdict $verdicts = null): void
    {
        $this->verdicts = $verdicts;
    }

    /**
     * @return LogBookSetup[]
     */
    public function getSetup(): ?array
    {
        return $this->setups;
    }

    /**
     * @param LogBookSetup[] $setups
     */
    public function setSetup(LogBookSetup $setups = null): void
    {
        $this->setups = $setups;
    }


}

templates/lbook/cycle/edit.html.twig
{% extends 'lbook/default/index.html.twig' %}

{% block content %}
    <h1>Cycle edit</h1>

    {{ form_start(edit_form, { 'attr': {'id': 'cycleEditForm'} }) }}
        {{ form_widget(edit_form) }}
        {#<input type="submit" value="Edit" />#}
    {{ form_end(edit_form) }}
    <div class="row">
        <div class="col-12 col-md-2">
            {% if is_granted('delete', cycle.setup) %}
                {{ form_start(delete_form, { 'attr': {'id': 'cycleEditFormDelete'} }) }}
                <button id="cycleEditDelete" class="btn btn-white btn-warning btn-bold" name="delete">
                    <i class="ace-icon fa fa-trash-o bigger-120 orange"></i>
                    Delete
                </button>
                {{ form_end(delete_form) }}
            {% endif %}
        </div>

        <div class="col-12 col-md-2">
            <button id="cycleEditSave" class="btn btn-white btn-info btn-bold" name="save">
                <i class="ace-icon fa fa-floppy-o bigger-120 blue"></i>
                Save
            </button>
            <button id="cycleEditCancel" class="btn btn-white btn-default btn-round" name="cancel" title="Cancel edit and go to cycle">
                <i class="ace-icon fa fa-times red2"></i>
                Cancel
            </button>
        </div>

        <div class="col-12 col-md-8">
        </div>
    </div>

    <script>
        $(document).ready(function() {
            $( "#cycleEditForm form" ).css( "width", "800px" );
            $( "#cycleEditForm input[type = 'text']" ).css( "width", "400px" );
            $( "#cycleEditForm select" ).css( "width", "400px" );
            $( "#cycleEditForm label" ).css( "width", "400px" );
            $( "#cycleEditCancel, button[name = 'cancel'].btn" ).bind( "click", function() {
                window.location.href = "{{ path('cycle_show_first', { 'id': cycle.id }) }}";
            });

            $( "#cycleEditDelete, button[name = 'delete'].btn" ).bind( "click", function() {
                var status = confirm("Are you sure about delete this cycle [{{ cycle.name }}]?");
                if (status === true) {
                    $("#cycleEditFormDelete").submit();
                } else {
                    return false;
                }
            });

            $( "#cycleEditSave, button[name = 'save'].btn" ).bind( "click", function() {
                $("#cycleEditForm").submit();
            });
        });
    </script>
{% endblock %}

templates/lbook/cycle/infobox.html.twig
{% spaceless %}
<div class="infobox-container">
    <div class="infobox infobox-orange2" style="width: 180px !important;">
        <div class="infobox-icon">
            <i class="ace-icon fa fa-flask"></i>
        </div>
        <div class="infobox-data" title="Also there is {{ cycle.testsDisabled }}({{ getPercentage (cycle.testsDisabled, allTestsCount, 2) }}%) disabled tests.">
            <span class="infobox-data-number">{{ testsCount }}</span>
            <div class="infobox-content">Total {{ allTestsCount}}
                <i class="ace-icon fa fa-exclamation-circle" title="All Tests count - Disabled tests also included"></i></div>
        </div>
    </div>

    <div class="infobox infobox-green">
        <div class="infobox-progress">
            <div class="easy-pie-chart percentage" id="passRate" data-size="50" data-percent="{{ cycle.passRate }}" data-color="#82af6f">
                <span class="percent">{{ cycle.testsPass | getPercentage (testsCount, 1) }}%</span>
            </div>
        </div>
        <div class="infobox-data" title="Pass Rate - {{ cycle.passRate }}%">
            <span class="infobox-text" style="color: #82af6f">Pass</span>
            <div class="infobox-content">
                <span class="bigger-110">{{ cycle.testsPass }}</span>
            </div>
        </div>
    </div>
    {% if cycle.testsWarning > 0 %}
        <div class="infobox infobox-black">
            <div class="infobox-progress">
                <div class="easy-pie-chart percentage" data-size="45" data-percent="{{ cycle.warningRate }}" data-color="#6FB3E0">
                    <span class="percent">{{ cycle.testsWarning |  getPercentage (testsCount, 1) }}%</span>
                </div>
            </div>
            <div class="infobox-data" title="Warning Rate - {{ cycle.warningRate }}%">
                <span class="infobox-text" style="color: #6FB3E0">Warning</span>
                <div class="infobox-content">
                    <span class="bigger-110">{{ cycle.testsWarning }}</span>
                </div>
            </div>
        </div>
    {% endif %}

    {% if cycle.testsFail > 0 %}
        <div class="infobox infobox-red">
            <div class="infobox-progress">
                <div class="easy-pie-chart percentage" data-size="45" data-percent="{{ cycle.failRate }}" data-color="#d15b47">
                    <span class="percent">{{ cycle.testsFail | getPercentage (testsCount, 1) }}%</span>
                </div>
            </div>
            <div class="infobox-data" title="Fail Rate - {{ cycle.failRate }}%">
                <span class="infobox-text" style="color: #d15b47">Fail</span>
                <div class="infobox-content">
                    <span class="bigger-115">{{ cycle.testsFail }}</span>
                </div>
            </div>
        </div>
    {% endif %}

    {% if cycle.testsError > 0 %}
        <div class="infobox infobox-orange">
            <div class="infobox-progress">
                <div class="easy-pie-chart percentage" data-size="45" data-percent="{{ cycle.errorRate }}" data-color="#f89406">
                    <span class="percent">{{ cycle.testsError |  getPercentage (testsCount, 1) }}%</span>
                </div>
            </div>
            <div class="infobox-data" title="Error Rate - {{ cycle.errorRate }}%">
                <span class="infobox-text" style="color: #f89406">Error</span>
                <div class="infobox-content">
                    <span class="bigger-115">{{ cycle.testsError }}</span>
                </div>
            </div>
        </div>
    {% endif %}

    {% if cycle.testsNa > 0 %}
        <div class="infobox infobox-blue">
            <div class="infobox-progress">
                <div class="easy-pie-chart percentage" data-size="45" data-percent="{{ cycle.naRate }}" data-color="#1da8f8">
                    <span class="percent">{{ cycle.testsNa |  getPercentage (testsCount, 1) }}%</span>
                </div>
            </div>
            <div class="infobox-data" title="Not available Rate - {{ cycle.naRate }}%">
                <span class="infobox-text" style="color: #1da8f8">NA</span>
                <div class="infobox-content">
                    <span class="bigger-110">{{ cycle.testsNa }}</span>
                </div>
            </div>
        </div>
    {% endif %}

    {% if cycle.testsUnknown > 0 %}
        <div class="infobox infobox-grey">
            <div class="infobox-progress">
                <div class="easy-pie-chart percentage" data-size="45" data-percent="{{ cycle.unknownRate }}" data-color="#abbac3">
                    <span class="percent">{{ cycle.testsUnknown |  getPercentage (testsCount, 1) }}%</span>
                </div>
            </div>
            <div class="infobox-data" title="Unknown Rate - {{ cycle.unknownRate }}%">
                <span class="infobox-text" style="color: #abbac3">Unknown</span>
                <div class="infobox-content">
                    <span class="bigger-110">{{ cycle.testsUnknown }}</span>
                </div>
            </div>
        </div>
    {% endif %}
    <div class="infobox infobox-black" style="width: 160px !important;">
        <div class="infobox-data" title="Run Time">
            <span class="infobox-text">{{ cycle.testsTimeSum |  ExecutionTimeGeneric }}</span>
            <div class="infobox-content">
                <span class="bigger-110" title="TestsTimeSum:Time in seconds calculated from all execution time of tests">Run Time</span>
            </div>
        </div>
    </div>
</div>
{% endspaceless %}

templates/lbook/cycle/new.html.twig
{% extends 'lbook/default/index.html.twig' %}

{% block content %}
    <h1>Cycle creation</h1>

    {{ form_start(form) }}
        {{ form_widget(form) }}
        <input type="submit" value="Create" />
    {{ form_end(form) }}

    <ul>
        <li>
            <a href="{{ path('cycle_index') }}">Back to the list</a>
        </li>
    </ul>
{% endblock %}

templates/lbook/cycle/show.html.twig
{% extends 'lbook/default/index.html.twig' %}
{% block title %}LBOOK Cycle [{{ cycle.id }}:{{ cycle.name }}] {% endblock %}
{% block content %}
    <h1>Cycle [{{ cycle.id }}] : {{ cycle.name }}</h1>

    <table class="records_list table table-striped table-condensed">
        <tbody>
            <tr>
                <th>
                    <span title="Time in seconds between min tests time to max tests time">Period</span>
                    /
                    <span title="testsTimeSum:Time in seconds calculated from all execution time of tests">Run Time</span>
                </th>
                <td>{{ cycle.period |  ExecutionTimeGeneric}} / {{ cycle.testsTimeSum |  ExecutionTimeGeneric}} </td>
                <th>Pass Rate</th>
                <td><span class="label label-danger label-white middle">{{ cycle.passRate }} %</span></td>
                <th>Name</th>
                <td><span class="label label-info label-white">{{ cycle.name }}</span></td>
                <th>Id</th>
                <td>{{ cycle.id }}</td>

            </tr>
            <tr>
                <th>Controller</th>
                <td><span class="label label-success label-white middle">{{ cycle.controller }}</span></td>
                <th>DUT</th>
                <td><span class="label label-success label-white middle">{{ cycle.dut }}</span></td>
                <th>Uploader</th>
                <td><span class="label label-success label-white middle">{{ cycle.targetUploader }}</span></td>
                <th>Build</th>
                <td><span class="label label-success label-white middle">{{ cycle.build }}</span></td>
            </tr>
            <tr>
                <th>Start Time</th>
                <td>{{ cycle.timeStart|date('Y-m-d H:i:s') }}</td>
                <th>End Time</th>
                <td>{{ cycle.timeEnd|date('Y-m-d H:i:s') }}</td>
                <th>Updated</th>
                <td>{{ cycle.updatedAt|date('Y-m-d H:i:s') }}</td>
                <th>Created</th>
                <td>{{ cycle.createdAt|date('Y-m-d H:i:s') }}</td>
            </tr>
            <tr>
                <th></th>
                <td></td>
                <th></th>
                <td></td>
                <th>Token</th>
                <td>{{ cycle.uploadToken }}</td>
                <th>Token EXP</th>
                <td>{{ cycle.tokenExpiration|date('Y-m-d H:i:s') }}</td>
            </tr>
            <tr>
                <th>Tests count</th>
                <td>{{ cycle.tests|length }}</td>
                <th>Setup</th>
                <td colspan="5">
                    <table class="records_list table table-striped table-condensed">
                        <tr>
                            <td><a target="_blank" href="{{ path('setup_show', { 'id': cycle.setup.id }) }}"><span class="label label-success label-white middle">{{ cycle.setup}}</span></a></td>
                            <td>Short name <span class="label label-success label-white middle">{{ cycle.setup.nameShown }}</span></td>
                            <td>OS :{{ cycle.setup.os }}</td>
                            <td>Owner :{{ cycle.setup.owner }}</td>
                        </tr>
                    </table>
                </td>
            </tr>
            <tr>
                <th>Pass</th>
                <td>{{ cycle.testsPass }}</td>
                <th>Fail</th>
                <td>{{ cycle.testsFail }}</td>
                <th>Error</th>
                <td>{{ cycle.testsError }}</td>
                <th>Count</th>
                <td>{{ cycle.testsCount }}</td>
            </tr>
            {% set already_printed = [ 'testsPass', 'testsFail', 'testsError', 'testsCount', 'dirty', 'uploadToken', 'tokenExpiration', 'id', 'name' , 'tests', 'setup', 'period', 'passRate', 'timeStart', 'timeEnd', 'updatedAt', 'createdAt', 'testsTimeSum', 'controller', 'targetUploader', 'dut', 'build'] %}
            {% for key, value in cycle|cast_to_array %}
                {% if key not in already_printed%}
                    <tr>
                        <th>{{ key | capitalize}}</th>
                        <td>{{ dump(value) }}</td>
                    </tr>
                {% endif %}
            {% endfor %}
        </tbody>
    </table>
    {%  set tests = cycle.tests%}
    {% include "lbook/search.html.twig" %}
    <table class="records_list table table-striped table-condensed table-hover">
        <thead>
        <tr>
            <th>id</th>
            <th>Order</th>
            <th>Name</th>
            <th>Time start</th>
            <th>Time end</th>
            <th>Runtime</th>
            <th>Uptime</th>
            <th>Uptime</th>
            <th>Verdict</th>
            {#<th>Actions</th>#}
        </tr>
        </thead>
        <tbody class="searchable">
        {% for test in tests %}
            <tr>
                {#<td><a href="{{ path('test_show_first', { 'id': test.id }) }}">{{ test.id }}</a></td>#}
                <td>{{ test.id }}</td>
                <td>{{ test.executionOrder }}</td>
                {#<td><a href="{{ path('test_show_first', { 'id': test.id }) }}">{{ test.name }}</a></td>#}
                <td><a href="{{ path('test_show_first', { 'id': test.id  }) }}">{{ test.name }}</a></td>
                <td>{% if test.timeStart %}{{ test.timeStart|date('Y-m-d H:i:s') }}{% endif %}</td>
                <td>{% if test.timeEnd %}{{ test.timeEnd|date('Y-m-d H:i:s') }}{% endif %}</td>
                <td>{{ test.timeRun | ExecutionTimeGeneric}}</td>
                <td>{{ test.dutUpTimeStart }}</td>
                <td>{{ test.dutUpTimeEnd }}</td>
                <td><span class="badge {{ verdictToBadge(test.verdict)}}">
                        {{ test.verdict }}
                    </span></td>
                {#<td>#}
                    {#<a href="{{ path('test_show_first', { 'id': test.id }) }}">show</a>#}
                    {#<a href="{{ path('test_edit', { 'id': test.id }) }}">edit</a>#}
                {#</td>#}
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <ul>
        <li>
            <a href="{{ path('cycle_index') }}">Back to the list</a>
        </li>
        {% if is_granted('edit', cycle.setup) %}
        <li>
            <a href="{{ path('cycle_edit', { 'id': cycle.id }) }}">Edit</a>
        </li>
        {% endif %}
        {#{% if is_granted('delete', cycle.setup) %}#}
        {#<li>#}
            {#{{ form_start(delete_form) }}#}
                {#<input type="submit" value="Delete" onclick="return confirm('are u sure?')">#}
            {#{{ form_end(delete_form) }}#}
        {#</li>#}
        {#{% endif %}#}
    </ul>
{% endblock %}