src/Entity/LogBookSetup.php
<?php

namespace App\Entity;

use App\Model\OsType;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\PreFlush;
use Doctrine\ORM\Mapping\PrePersist;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LogBookSetupRepository")
 * @ORM\Table(name="lbook_setups")
 * @UniqueEntity("name", message="Setup with this name already exist")
 * @ORM\HasLifecycleCallbacks()
 */
class LogBookSetup
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer", options={"unsigned"=true})
     */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     * @Assert\NotBlank(message="Test Verdict name cannot ne empty")
     */
    protected $name = '';

    /**
     * @var string
     *
     * @ORM\Column(name="name_shown", type="string", length=50, nullable=true)
     */
    protected $nameShown = '';

    /**
     * @var bool
     *
     * @ORM\Column(name="is_disabled", type="boolean", options={"default" : "0"})
     */
    protected $disabled = false;

    /**
     * @var integer
     *
     * @ORM\Column(name="os", type="smallint", nullable=true)
     */
    protected $os = 0;

    /**
     * @var bool
     *
     * @ORM\Column(name="check_up_time", type="boolean", options={"default" : "0"})
     */
    protected $checkUpTime = false;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\LogBookUser", fetch="EXTRA_LAZY")
     * @ORM\JoinColumn(name="owner", referencedColumnName="id", nullable=true)
     */
    protected $owner = 0;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\LogBookUser", fetch="EXTRA_LAZY")
     */
    protected $moderators;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\LogBookCycle", mappedBy="setup", cascade={"all"}, fetch="EXTRA_LAZY")
     * @ORM\JoinColumn(name="cycles", fieldName="id", referencedColumnName="id")
     * @ORM\OrderBy({"id" = "DESC"})
     */
    protected $cycles;

    /**
     * @var boolean
     *
     * @ORM\Column(name="is_private", type="boolean", options={"default"=false})
     */
    protected $isPrivate = false;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="created_at", type="datetime", nullable=false, options={"default"="CURRENT_TIMESTAMP"})
     * //@Assert\DateTime()
     */
    protected $createdAt;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="updated_at", type="datetime", nullable=true, options={"default"="CURRENT_TIMESTAMP"})
     * //@Assert\DateTime()
     */
    protected $updatedAt;

    /**
     * @var integer
     *
     * @ORM\Column(name="retention_policy", type="smallint", options={"unsigned"=true, "default"="400"})
     */
    protected $retentionPolicy = 400;

    public static $MIN_NAME_LEN = 2;
    public static $MAX_NAME_LEN = 250;

    /**
     * LogBookSetup constructor.
     */
    public function __construct()
    {
        $this->setUpdatedAt();
        $this->setCreatedAt();
        $this->moderators = new ArrayCollection();
        $this->cycles = new ArrayCollection();
        $this->setRetentionPolicy(90);
    }

    /**
     * @return int
     */
    public function getRetentionPolicy(): int
    {
        return $this->retentionPolicy;
    }

    /**
     * @param int $retentionPolicy
     */
    public function setRetentionPolicy(int $retentionPolicy): void
    {
        $this->retentionPolicy = $retentionPolicy;
    }


    /**
     * @return mixed
     */
    public function getOwner()
    {
        return $this->owner;
    }

    /**
     * @param mixed $owner
     */
    public function setOwner($owner): void
    {
        $this->owner = $owner;
    }

    /**
     * @return bool
     */
    public function isPrivate(): bool
    {
        return $this->isPrivate;
    }

    /**
     * @param bool $isPrivate
     */
    public function setIsPrivate(bool $isPrivate): void
    {
        $this->isPrivate = $isPrivate;
    }

    /**
     * @return Collection|LogBookUser[]
     */
    public function getModerators(): Collection
    {
        return $this->moderators;
    }

    /**
     * @param Collection $moderators
     */
    public function setModerators(Collection $moderators): void
    {
        $this->moderators = $moderators;
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id): void
    {
        $this->id = $id;
    }

    /**
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }

    public static function validateName($newName): string
    {
        if (mb_strlen($newName) > self::$MAX_NAME_LEN) {
            $newName = mb_substr($newName, 0, self::$MAX_NAME_LEN);
        }
        return $newName;
    }

    /**
     * @param string $name
     */
    public function setName(string $name): void
    {
        $this->name = self::validateName($name);
    }

    public function __toString(): string
    {
        return $this->getName();
    }

    /**
     * @return string
     */
    public function getNameShown(): ?string
    {
        if (\strlen($this->nameShown)>0) {
            return $this->nameShown;
        }

        return $this->getName();
    }

    /**
     * @param string $nameShown
     */
    public function setNameShown(string $nameShown=null): void
    {
        $this->nameShown = $nameShown;
    }

    /**
     * @return bool
     */
    public function isDisabled(): bool
    {
        return $this->disabled;
    }

    /**
     * @param bool $disabled
     */
    public function setDisabled(bool $disabled): void
    {
        $this->disabled = $disabled;
    }

    /**
     * @return mixed
     */
    public function getOs()
    {
        return $this->os;
    }

    /**
     * @return string
     */
    public function getOsStr(): string
    {
        return OsType::getTypeName($this->getOs());
    }

    /**
     * @param $os
     */
    public function setOs($os): void
    {
        $this->os = $os;
    }

    /**
     * @return bool
     */
    public function isCheckUpTime(): bool
    {
        return $this->checkUpTime;
    }

    /**
     * @param bool $checkUpTime
     */
    public function setCheckUpTime(bool $checkUpTime): void
    {
        $this->checkUpTime = $checkUpTime;
    }

    /**
     * @return Collection|LogBookCycle[]
     */
    public function getCycles(): Collection
    {
        return $this->cycles;
    }

    /**
     * @param Collection $cycles
     */
    public function setCycles($cycles): void
    {
        $this->cycles = $cycles;
    }

    /**
     * @return \DateTime
     */
    public function getCreatedAt(): \DateTime
    {
        return $this->createdAt;
    }

    /**
     * @PrePersist
     */
    public function setCreatedAt(): void
    {
        $this->createdAt = new \DateTime();
    }

    /**
     * @return \DateTime
     */
    public function getUpdatedAt(): \DateTime
    {
        return $this->updatedAt;
    }

    /**
     * @PreFlush
     * @PrePersist
     */
    public function setUpdatedAt(): void
    {
        $this->updatedAt = new \DateTime();
    }
}

templates/lbook/setup/cycle.paginator.html.twig
{% set currentPath = path(app.request.get('_route'), app.request.get('_route_params')) %}
    {% set currentPage = thisPage %}
    {% set left     = thisPage-10 %}
    {% set right    = thisPage+10 %}
    {% set start    = 2 %}
    {% set end      = maxPages -1 %}

    {% if maxPages > 1 %}
        {% if left < 1 %}
            {% set left = 1 %}
        {% endif %}

        {% if right > maxPages %}
            {% set right = maxPages %}
        {% endif %}


        <ul class="pagination pagination-sm">
            {# `«` arrow  #}
            <li {{ thisPage == 1 ? 'class="disabled"' }} >
                <a href="{{ path(pagePath, {id: setupId, page: thisPage-1 < 1 ? 1 : thisPage-1}) }}">«</a>
            </li>

            {% if left < thisPage and  start < left %}

                {% for i in 1..start %}
                    <li class="page-item {{ thisPage == i ? 'active' }}">
                        <a class="page-link" href="{{ path( pagePath, {id: setupId, page: i}) }}"  style="background-color:#EAEAEA;">{{ i }}</a>
                    </li>

                {% endfor %}
            {% endif %}


            {% if left <= thisPage and right >= thisPage %}

                {% for i in left..right %}
                    <li class="page-item {{ thisPage == i ? 'active' }}">
                        <a class="page-link" href="{{ path(pagePath, {id: setupId, page: i}) }}">{{ i }}</a>
                    </li>
                {% endfor %}

            {% endif %}

            {% if right > thisPage and end > right  %}

                {% for i in end..maxPages %}
                    <li class="page-item {{ thisPage == i ? 'active' }}">
                        <a class="page-link" href="{{ path(pagePath, {id: setupId, page: i}) }}" style="background-color:#EAEAEA">{{ i }}</a>
                    </li>
                {% endfor %}

            {% endif %}

            {# `»` arrow #}
            <li {{ thisPage == maxPages ? 'class="disabled"' }}>
                <a href="{{ path(pagePath, {id: setupId, page: thisPage+1 <= maxPages ? thisPage+1 : thisPage}) }}">»</a>
            </li>
        </ul>
    {% endif %}

templates/lbook/setup/edit.html.twig
{% extends 'lbook/default/index.html.twig' %}

{% block content %}
    <h1>Setup edit</h1>

    {{ form_start(edit_form) }}
        {{ form_widget(edit_form) }}
        <input type="submit" value="Edit" />
    {{ form_end(edit_form) }}
    <div class="well well-lg">
        <h4 class="green smaller lighter">Options</h4>
        <ul class="list-inline">
            <li>
                <i class="ace-icon fa fa-share green bigger-110"></i>
                <a href="{{ path('setup_show', { 'id': setup.id }) }}">Back to Setup</a>
            </li>
            <li>
                <a href="{{ path('setup_index') }}">Back to the list</a>
            </li>
            {% if is_granted('delete', setup) %}
                {% if delete_form is not null %}
                    <li>
                        {{ form_start(delete_form) }}
                        <input type="submit" value="Delete" onclick="return confirm('Are you sure about delete this setup?')">
                        {{ form_end(delete_form) }}
                    </li>
                {%  endif %}
            {%  endif %}
        </ul>
    </div>

{% endblock %}

templates/lbook/setup/index.html.twig
{% extends 'lbook/default/index.html.twig' %}
{% block title %}LBOOK Setup list{% endblock %}
{% block content %}
    <h1 style="margin-top: 0 !important;">Setup list</h1>
    <div>Count : {{ size }}</div>
    {% include "lbook/search.html.twig" %}
    {% set pagePath = "setup_index" %}
    <div class="row">
        <div class="col-sm-12 text-center">{% include "lbook/paginator.html.twig" %}</div>
    </div>
    <div class="row">
        <div id="setupTableToolbar">
        </div>
        {% spaceless %}
        <table class="records_list table table-striped table-condensed table-hover" data-classes="table table-no-bordered"
               id="setupTable" data-pagination="true" data-search="true" data-toggle="table"
               data-toolbar="#setupTableToolbar"
               data-show-refresh="true"
               data-key-events="true"
                {#data-show-toggle="true"#}
               data-show-export="true"
               data-show-columns="true"
               data-advanced-search="true"
               {#data-id-table="advancedTable"#}
               data-page-size="100" data-page-list="[5, 10, 20, 50, 100, 500]" data-sort-order="desc">
            <thead>
            <tr>
                <th data-sortable="true" title="Updated image" class="time_diff_icon" data-switchable="false">&nbsp;</th>
                <th data-sortable="true" data-switchable="false">ID</th>
                <th data-sorter="htmlSorter" data-sortable="true" title="Full setup name" data-switchable="false">Name</th>
                <th data-sortable="true" title="Cycles found">Cycles</th>
                <th data-sorter="dataTitleDateSorter" data-sortable="true" title="Update time">Updated</th>
                <th data-sortable="true">OS</th>
                <th data-sortable="true" title="Owner Name">Owner</th>
                <th data-sorter="dataTitleDateSorter" data-sortable="true" title="Created time" data-visible="false">Created</th>
                <th data-sortable="true" title="Check Uptime" data-visible="false">UPT</th>
                <th data-sortable="true" title="Moderators cound" data-visible="false">Moderators</th>
                <th data-sortable="true" title="Shows if the setup is disabled" data-visible="false">Disabled</th>
                <th data-sortable="true" title="Is it marked as Private" data-visible="false">Private</th>
                <th class="setup_list_options_column">Options</th>
            </tr>
            </thead>
            <tbody class="searchable">
            {% set break = false %}
            {% set counter = 0 %}
            {% for setup in iterator if not break %}
            {% if counter == 10000 %}
                {% set break = true %}
            {% endif %}
            {% set counter = counter+1 %}
                <tr>
                    <td title="Updated {{ setup.updatedAt|time_diff }}">
                        {% if date(setup.updatedAt) > date('-5 minutes') %}
                            <i class="normal-icon ace-icon fa fa-clock-o red smaller-90"></i>
                        {% elseif date(setup.updatedAt) > date('-30 minutes') %}
                            <i class="normal-icon ace-icon fa fa-clock-o pink smaller-80"></i>
                        {% elseif date(setup.updatedAt) > date('-60 minutes') %}
                            <i class="normal-icon ace-icon fa fa-clock-o blue smaller-70"></i>
                        {% elseif date(setup.updatedAt) > date('-12 hours') %}
                            <i class="normal-icon ace-icon fa fa-clock-o yellow smaller-70"></i>
                        {% endif %}
                    </td>
                    {% set setup_name = setup.name %}
                    {% if setup.name != setup.nameShown and setup.nameShown != '' %}
                        {% set setup_name = setup.nameShown %}
                    {% endif %}
                    <td>{{ setup.id }}</td>
                    <td><a href="{{ path('setup_show_first', { 'id': setup.id }) }}">{{ setup_name }}</a></td>
                    <td>{{ setup.cycles | length }}</td>
                    <td><span data-title="{{ setup.updatedAt|date('ymdHis') }}" title="Updated at {{ setup.updatedAt|date('d/m/Y H:i:s') }}">{{ setup.updatedAt|time_diff}}</span></td>
                    <td>{{ setup.osStr }}</td>
                    <td>{{ setup.owner }}</td>
                    <td><span data-title="{{ setup.createdAt|date('ymdHis') }}" title="Created at {{ setup.createdAt|date('d/m/Y H:i:s') }}">{{ setup.createdAt|time_diff}}</span></td>
                    <td>{{ setup.checkUpTime ? 'Yes':'No' }}</td>
                    <td>{{ setup.moderators|length }}</td>
                    <td>{{ setup.disabled ? 'Yes':'False' }}</td>
                    <td>{{ setup.isPrivate ? 'Private':'Public' }}</td>
                    <td>
                        <div class="hidden-sm hidden-xs action-buttons">
                            <a class="blue" href="{{ path('setup_show', { 'id': setup.id }) }}" title="Show">
                                <i class="ace-icon fa fa-search-plus bigger-130"></i>
                            </a>
                            {% if is_granted('edit', setup) %}
                            <a class="green" href="{{ path('setup_edit', { 'id': setup.id }) }}" title="Edit">
                                <i class="ace-icon fa fa-pencil bigger-130"></i>
                            </a>
                            {% endif %}
                            {#<a class="red" href="#" title="Delete">#}
                                {#<i class="ace-icon fa fa-trash-o bigger-130"></i>#}
                            {#</a>#}
                        </div>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {% endspaceless %}
    </div>
    {% if app.user.roles is defined and 'ROLE_SUPER_ADMIN' in app.user.roles %}
        <div class="row">
            <ul>
                <li>
                    <a href="{{ path('setup_new') }}">Create a new setup</a>
                </li>
            </ul>
            <div class="well">
                <h4 class="green smaller lighter">Setup information</h4>
                Only ROLE_SUPER_ADMIN can add new setup
            </div>
        </div>
    {% endif %}
    <script>
        $(document).ready(function() {
            $( "#setupTableToolbar, button[name = 'refresh'].btn" ).bind( "click", function() {
                location.reload();
            });
            try {
                ace.settings.sidebar_collapsed(document.getElementById('sidebar'), true, true);
                ace.settings.sidebar_fixed(document.getElementById('sidebar'), true, true);
            } catch (e) {}
        });
    </script>
{% endblock %}

templates/lbook/setup/new.html.twig
{% extends 'lbook/default/index.html.twig' %}

{% block content %}
    <h1>Setup creation</h1>

    {{ form_start(form) }}
        {{ form_widget(form) }}
        <input type="submit" value="Create" />
    {{ form_end(form) }}

    <ul>
        <li>
            <a href="{{ path('setup_index') }}">Back to the list</a>
        </li>
    </ul>
{% endblock %}

templates/lbook/setup/show.full.html.twig
{% extends 'lbook/default/index.html.twig' %}
{% block title %}LogBOOK Setup [{{ setup.id }}:{{ setup.name }}] {% endblock %}
{% block content %}
    <h3 style="margin-top: 0 !important;">Setup [{{ setup.id }}] : {{ setup.name }}</h3>
    {% spaceless %}
    <table class="records_list table table-striped table-condensed">
        <tbody>
        <tr>
            <th>Short Name / OS</th>
            <td>
                <i class="ace-icon fa fa-bookmark"></i>
                {{ setup.nameShown }}
                /
                <span class="label label-lg label-yellow">{{ setup.osStr }}</span>
            </td>
            <th>
                <span style="float: right;">Created / Updated</span>
            </th>
            <td>
                <span style="float: right;">
                    <i class="ace-icon fa fa-calendar"></i>
                    <span class="blue">{{ setup.createdAt|date('d/m/Y H:i:s') }}</span>
                    /
                    <i class="ace-icon fa fa-calendar"></i>
                    <span class="blue">{{ setup.updatedAt|date('d/m/Y H:i:s') }}</span>
                    &nbsp;&nbsp;&nbsp;&nbsp;
                    <i class="ace-icon fa fa-info-circle" title="Show time diff when the setup was updated"></i>
                    {%  if date(setup.updatedAt) > date('-20minutes') %}
                        {% set updatedClass="red" %}
                    {% else %}
                        {% set updatedClass="blue" %}
                    {% endif %}
                    <span class="{{ updatedClass }}">{{ setup.updatedAt|time_diff}}</span>
                </span>
            </td>
        </tr>
        <tr>
            <th>Owners</th>
            <td>
                <span>
                    <i class="ace-icon fa fa-key" title="Owner"></i>
                    <span class="label label-sm label-success label-white arrowed arrowed-right">{{ setup.owner}}</span>
                    &nbsp;&nbsp;&nbsp;&nbsp;
                    <i class="ace-icon fa fa-users" title="Moderators"></i>
                    {% for moderator in setup.moderators %}
                        <a href="{{ path('user_show', { 'id': moderator.id }) }}" target="_blank">
                        {% if moderator.id == setup.owner.id %}
                            <span class="label label-sm label-danger label-white arrowed arrowed-right" title="Setup owner">{{ moderator.username }}</span>
                        {% else %}
                            <span class="label label-sm label-primary label-white arrowed arrowed-right">{{ moderator.username }}</span>
                        {% endif %}
                    </a>
                    {% endfor %}
                </span>
            </td>
            <th>
                <span style="float:right;">Disabled / Visibility / Check Uptime </span>
            </th>
            <td>
                <span style="float:right;">
                    <span class="blue">
                    {{ setup.disabled ? '<i class="ace-icon fa fa-lock" title="Disabled"></i> Disabled':'<i class="ace-icon fa fa-unlock" title="Enabled"></i> Enabled' }}
                    </span>
                    /
                    <span class="green">
                    {{ setup.private ? '<i class="ace-icon fa fa-eye"></i> Private':'<i class="ace-icon fa fa-globe"></i> Public' }}
                    </span>
                    /
                    <span class="yellow">
                    {{ setup.checkUpTime ? '<i class="ace-icon fa fa-check-square-o"></i> Yes':'<i class="ace-icon fa fa-ban"></i> No' }}
                    </span>
                </span>
            </td>
        </tr>

        {% set already_printed = ['moderators', 'id', 'name', 'cycles', 'nameShown', 'createdAt', 'updatedAt', 'owner', 'disabled', 'os', 'isPrivate', 'checkUpTime', 'MAX_NAME_LEN', 'MIN_NAME_LEN'] %}
        {% for key, value in setup|cast_to_array %}
            {% if key not in already_printed%}
                <tr>
                    <th>{{ key | capitalize}}</th>
                    <td>{{ value }}</td>
                </tr>
            {% endif %}
        {% endfor %}
        </tbody>
    </table>
    {% endspaceless %}
    {% set pagePath = "setup_show" %}
    {% set objId = setup.id %}
    {% include "lbook/double.paginator.html.twig" %}
    {%  set cycles = setup.cycles %}
    <div>Count : {{ size }}</div>
    {% include "lbook/search.html.twig" %}
    <div id="toolbarSetupsList">
    </div>
    {% spaceless %}
    <table class="records_list table table-striped table-condensed table-hover" data-classes="table table-no-bordered" id="setupCycleList"
           data-pagination="true" data-search="true" data-toggle="table"
           data-show-columns="true" data-show-refresh="true"
           {#data-detail-view="true"#}
           {#data-detail-formatter="detailFormatter"#}
           {#data-show-refresh="true" data-show-toggle="true" data-show-fullscreen="true"#}
           data-toolbar="#toolbarSetupsList"
           data-page-size="500" data-page-list="[20, 50, 100, 500, 1000, 'ALL']" data-sort-order="desc">
        <thead>
        <tr>
            <th data-sortable="true" title="Updated image" class="time_diff_icon" data-switchable="false">&nbsp;</th>
            <th class="setup_cycle_id_column" data-sorter="htmlSorter" data-sortable="true">Id</th>
            <th data-sorter="htmlSorter" data-sortable="true" class="setup_cycle_name_column" data-switchable="false">Name</th>
            <th class="setup_cycle_tests_column" data-sortable="true">Tests</th>
            {%  if show_build %}
            <th class="setup_cycle_build_column" data-sorter="htmlSorter" data-sortable="true">Build</th>
            {% endif %}
            {%  if show_user %}
            <th class="setup_cycle_user" data-sortable="true">User</th>
            {% endif %}
            <th class="setup_cycle_passrate_column" data-sorter="dataPercentSorter" data-sortable="true" title="Pass Rate">Pass %</th>
            <th class="setup_cycle_period_column" data-sortable="true" data-sorter="dataTitleIntSorter" title="Time duration between First test start-time and Last test end-time">Duration</th>
            <th class="setup_cycle_testtime_column" data-sortable="true" data-sorter="dataTitleIntSorter" title="The total summary time of all tests in this cycle">Test time</th>
            <th class="setup_cycle_updated_column" data-sorter="htmlSorter" data-sortable="true">Updated</th>
            {#<th data-sortable="true" data-visible="false">Controller</th>#}
            {#<th data-sortable="true" data-visible="false">DUT</th>#}
            <th class="setup_cycle_uploader_column" data-sortable="true" data-visible="false">Uploader</th>
            <th class="setup_cycle_options_column" data-switchable="false">Options</th>
        </tr>
        </thead>
        <tbody class="searchable">
        {% set break = false %}
        {% set counter = 0 %}
        {% for cycle in iterator if not break %}
            {% if counter == 10000 %}
                {% set break = true %}
            {% endif %}
            {% set counter = counter+1 %}
            <tr>
                <td title="Updated {{ cycle.updatedAt|time_diff }}">
                    {% if date(cycle.updatedAt) > date('-5 minutes') %}
                        <i class="normal-icon ace-icon fa fa-clock-o red smaller-90"></i>
                    {% elseif date(cycle.updatedAt) > date('-30 minutes') %}
                        <i class="normal-icon ace-icon fa fa-clock-o pink smaller-80"></i>
                    {% elseif date(cycle.updatedAt) > date('-60 minutes') %}
                        <i class="normal-icon ace-icon fa fa-clock-o blue smaller-70"></i>
                    {% elseif date(cycle.updatedAt) > date('-12 hours') %}
                        <i class="normal-icon ace-icon fa fa-clock-o yellow smaller-70"></i>
                    {% endif %}
                </td>
                <td>
                    <a href="{{ path('cycle_show_first', { 'id': cycle.id }) }}">{{ cycle.id }}</a>
                </td>
                <td title="{{ cycle.name }}">
                    <a href="{{ path('cycle_show_first', { 'id': cycle.id }) }}">{{ shortString(cycle.name, 65, "...") }}</a>
                </td>
                <td>{{ cycle.testsCount }}</td>
                {%  if show_build %}
                <td title="{{ cycle.build }}">
                    {% if cycle.build.id is defined %}
                        <a href="{{ path('build_show_cycles', { 'id': cycle.build.id }) }}">{{ shortString(cycle.build, 35, "...") }}</a>
                    {% endif %}
                </td>
                {% endif %}
                {%  if show_user %}
                <td title="{{ cycle.user.FullName }}">{{ cycle.user.UserNameMedium }}</td>
                {% endif %}
                <td><span class="{{ passRateToColor(cycle.passRate) }}" data-percent="{{ cycle.passRate }}">{{ cycle.passRate }}%</span></td>
                <td><span data-title="{{ cycle.period  }}">{{ cycle.period |  ExecutionTimeGeneric}}</span></td>
                <td><span data-title="{{ cycle.testsTimeSum  }}">{{ cycle.testsTimeSum |  ExecutionTimeGeneric}}</span></td>
                <td>
                    <span title="{{ cycle.updatedAt|time_diff }}">
                        {{ cycle.updatedAt |date('d/m H:i:s') }}
                    </span>
                </td>
                {#<td>{{ cycle.controller }}</td>#}
                {#<td>{{ cycle.dut }}</td>#}
                <td>{{ cycle.targetUploader }}</td>
                <td>
                    <div class="hidden-sm hidden-xs action-buttons">
                        <a class="blue" href="{{ path('cycle_show', { 'id': cycle.id }) }}" title="Show">
                            <i class="ace-icon fa fa-search-plus bigger-130"></i>
                        </a>
                        {% if is_granted('edit', setup) %}
                            <a class="green" href="{{ path('cycle_edit', { 'id': cycle.id }) }}" title="Edit">
                                <i class="ace-icon fa fa-pencil bigger-130"></i>
                            </a>
                        {% endif %}
                        {#<a class="red" href="#" title="Delete">#}
                        {#<i class="ace-icon fa fa-trash-o bigger-130"></i>#}
                        {#</a>#}
                    </div>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% endspaceless %}
    {% spaceless %}
    <ul>
        <li>
            <a href="{{ path('setup_index') }}">Back to setup list</a>
        </li>
        {% if is_granted('edit', setup) %}
            <li><a href="{{ path('setup_edit', { 'id': setup.id }) }}">Edit</a></li>
            <div class="well">
                <h4 class="green smaller lighter">Edit information</h4>
                Only setup owner and setup administrator can edit this setup
            </div>
        {% endif %}
        {#{% if is_granted('delete', setup) %}#}
        {#<li>#}
        {#{{ form_start(delete_form) }}#}
        {#<input type="submit" value="Delete" onclick="return confirm('Are you sure about delete this setup?')">#}
        {#{{ form_end(delete_form) }}#}
        {#</li>#}
        {#{% endif %}#}
    </ul>
    <script>
        function detailFormatter(index, row) {
            var html = [];
            $.each(row, function (key, value) {
                if (!key.startsWith('_')) {
                    html.push('<p><b>' + key + ':</b> ' + value + '</p>');
                }
            });
            return html.join('');
        }

        $(document).ready(function() {
            $( "#toolbarSetupsList, button[name = 'refresh'].btn" ).bind( "click", function() {
                location.reload();
            });

            try {
                ace.settings.sidebar_collapsed(document.getElementById('sidebar'), true, true);
                ace.settings.sidebar_fixed(document.getElementById('sidebar'), true, true);
            } catch (e) {}
        });
    </script>
    {% endspaceless %}
{% endblock %}